// Drafts and uncertain submissions live only in memory, never in browser storage.
const drafts=new Map(),pending=new Map();
export function clearChatState(){drafts.clear();pending.clear();}
export async function readChatEvents(response,onStatus){
  const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',result;
  try{while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done}).replace(/\r\n/g,'\n');let end;
    while((end=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,end);buffer=buffer.slice(end+2);const event=block.split('\n').find(x=>x.startsWith('event:'))?.slice(6).trim();const data=block.split('\n').filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).join('\n');if(!data)continue;const payload=JSON.parse(data);if(event==='error')throw Object.assign(Error(payload.message),{status:payload.status});if(event==='status')onStatus(payload.message);if(event==='result')result=payload;}
    if(done)break;
  }}finally{reader.releaseLock();}
  if(!result)throw Error('Connection interrupted. Check the saved chat before retrying.');return result;
}
export function mountChats(host,{api,esc,active,scope=null,threadId=null,onChange=()=>{},onExpand=null}){
  let alive=true,generation=0,timer,thread=null,offset=0,query='',busy=false,sourceDialog,expanded=false;
  const valid=()=>alive&&active(),q=s=>host.querySelector(s),scopeLabel=t=>`${t.project_name||''}${t.topic_name?' / '+t.topic_name:' / All topics'}`;
  const draftKey=()=>thread?.id;
  const fail=e=>{if(valid()){q('[data-chat-error]').textContent=e.message;q('[data-chat-error]').hidden=false;}};
  host.innerHTML='<section class="chat-workspace"><div class="error" data-chat-error role="alert" hidden></div><div data-chat-body></div></section>';
  const body=q('[data-chat-body]');
  function button(text,attrs=''){return `<button type="button" class="secondary" ${attrs}>${text}</button>`;}
  async function work(fn){if(busy)return;busy=true;if(valid())q('[data-chat-error]').hidden=true;try{await fn();}catch(e){fail(e);}finally{busy=false;}}
  function stopPoll(){clearTimeout(timer);}
  async function history(){stopPoll();thread=null;const version=++generation;
    body.innerHTML=`<div class="chat-toolbar"><input data-chat-search aria-label="Search chats" placeholder="Search chats…" value="${esc(query)}">${button('New chat','data-chat-new')}</div>${scope?`<p class="helper">${esc(scope.project_name)}${scope.topic_name?' / '+esc(scope.topic_name):' / All topics'}</p>`:''}<div data-chat-list role="status">Loading chats…</div><div class="row" data-chat-pages></div>`;
    q('[data-chat-new]').onclick=()=>scope?create(scope):chooseScope();let searchTimer;
    q('[data-chat-search]').oninput=e=>{query=e.target.value;offset=0;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(valid()&&generation===version)loadList(version);},200);};await loadList(version);
  }
  async function loadList(version){const search=query,startOffset=offset;try{const data=await api(`/memories/chats?limit=30&offset=${offset}&q=${encodeURIComponent(query)}${scope?'&project_id='+scope.project_id+(scope.topic_id?'&topic_id='+scope.topic_id:''):''}`);if(!valid()||version!==generation||query!==search||offset!==startOffset)return;q('[data-chat-list]').innerHTML=data.items.length?data.items.map(t=>`<button class="chat-history-row" data-thread="${esc(t.id)}"><span>${esc(t.title)}</span><small>${esc(scopeLabel(t))} · ${esc(new Date(t.updated_at).toLocaleString())}</small></button>`).join(''):'<p class="empty">No chats yet. Start a new discussion with its own context.</p>';q('[data-chat-pages]').innerHTML=(offset?button('Previous','data-chat-prev'):'')+(data.has_more?button('More chats','data-chat-next'):'');host.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>load(b.dataset.thread));q('[data-chat-prev]')?.addEventListener('click',()=>{offset-=30;loadList(version);});q('[data-chat-next]')?.addEventListener('click',()=>{offset+=30;loadList(version);});}catch(e){fail(e);}}
  async function chooseScope(){const version=++generation;body.innerHTML='<p role="status">Loading projects…</p>';try{let projects=[],page=0,more=true;while(more&&page<1000){const d=await api(`/memories/projects?limit=100&offset=${page}`);projects.push(...d.items);more=d.has_more;page+=100;}if(!valid()||version!==generation)return;body.innerHTML=`<h2>New chat</h2><p class="helper">Choose its knowledge scope. Each discussion starts with a clean context.</p><label>Project<select data-project>${projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><label>Topic<select data-topic><option value="">All topics in this project</option></select></label><div class="row sectiongap">${button('Start chat','data-start')}${button('Cancel','data-cancel')}</div>${!projects.length?'<p>Create a project in Memories first.</p>':''}`;q('[data-start]').disabled=!projects.length;q('[data-cancel]').onclick=history;let seq=0;
    async function topics(){const id=q('[data-project]').value,n=++seq;q('[data-start]').disabled=true;try{const d=await api('/memories/projects/'+id);if(!valid()||version!==generation||n!==seq)return;q('[data-topic]').innerHTML='<option value="">All topics in this project</option>'+d.topics.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');q('[data-start]').disabled=false;}catch(e){fail(e);}}
    q('[data-project]').onchange=topics;q('[data-start]').onclick=()=>create({project_id:q('[data-project]').value,topic_id:q('[data-topic]').value||null});if(projects.length)topics();
  }catch(e){fail(e);}}
  async function create(s){const creatingGeneration=generation;await work(async()=>{const t=await api('/memories/chats',{method:'POST',body:JSON.stringify({project_id:s.project_id,topic_id:s.topic_id||null})});onChange();if(valid()&&generation===creatingGeneration)await load(t.id);});}
  async function load(id,quiet=false){stopPoll();const version=quiet?generation:++generation;if(!quiet&&thread?.id!==id){thread=null;body.innerHTML='<p role="status">Opening chat…</p>';}try{const data=await api('/memories/chats/'+id);if(!valid()||version!==generation)return;thread=data;
    const unresolved=pending.get(id),saved=unresolved&&data.turns.find(t=>t.request_id===unresolved.request_id);if(saved){pending.delete(id);if(drafts.get(id)===unresolved.question)drafts.delete(id);}
    draw();if(data.pending_turn_id)timer=setTimeout(()=>{if(valid()&&thread?.id===id)load(id,true);},4000);
  }catch(e){fail(e);}}
  function source(turn,id){const s=turn.response.sources.find(s=>s.id===id);if(!s)return;sourceDialog?.close();sourceDialog=document.createElement('dialog');sourceDialog.className='chat-source-dialog';sourceDialog.innerHTML=`<h2>Supporting evidence</h2><p>${esc(s.text)}</p>${(turn.changed_source_ids||[]).includes(id)?'<p class="notice">This evidence has changed since the saved answer.</p>':''}${s.evidence.map(e=>`<blockquote>${esc(e.evidence)}<p class="helper">${esc(e.source_title||'Conversation')} · ${esc(e.event_at||'')}</p></blockquote>`).join('')}<button class="secondary">Back to chat</button>`;const dialog=sourceDialog;dialog.querySelector('button').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();document.body.append(sourceDialog);sourceDialog.showModal();}
  function turnHTML(t){return `<article class="chat-turn" data-turn="${esc(t.id)}"><div class="chat-question"><small>You</small><p>${esc(t.question)}</p></div><div class="chat-answer"><small>Memory</small>${t.status==='running'?`<p role="status">Preparing a grounded answer…</p>${t.retry_after_seconds===0?button('Resume interrupted response',`data-retry="${esc(t.id)}"`):''}`:t.status==='failed'?`<p class="notice">${t.error==='sources_changed_retry'?'Sources changed while answering. Retry with current evidence.':'Answer unavailable. Your question is saved.'}</p>${button('Retry response',`data-retry="${esc(t.id)}"`)}`:t.response?.status==='no_evidence'?'<p>No accepted memories support an answer in this scope yet.</p>':(t.response?.claims||[]).map(c=>`<p>${esc(c.text)}</p><div class="chat-citations">${c.source_ids.map(id=>button('Source '+((t.response.sources||[]).findIndex(s=>s.id===id)+1),`data-citation="${esc(id)}" data-citation-turn="${esc(t.id)}"`)).join('')}</div>`).join('')}${t.changed_source_ids?.length?'<p class="helper">Evidence changed since this answer. New questions use current memories.</p>':''}${t.context_info?.omitted_turns?'<p class="helper">Earlier messages were omitted from this answer’s context.</p>':''}${t.response?.pending_changes?'<p class="helper">Some memory changes are still awaiting review.</p>':''}</div></article>`;}
  function draw(){const last=thread.turns.at(-1),blocked=!!thread.pending_turn_id||last?.status==='failed'||pending.has(thread.id);const draft=drafts.get(draftKey())||'';const previous=q('[data-composer]'),focus=previous===document.activeElement,start=previous?.selectionStart;
    body.innerHTML=`<header class="chat-thread-heading"><div><h2>${esc(thread.title)}</h2><p class="helper">${esc(scopeLabel(thread))}</p></div><div class="row">${button('History','data-history')}${button('New chat','data-new')}${button('Rename','data-rename')}${onExpand?button(expanded?'Return to pane':'Expand chat','data-expand'):''}</div></header>${thread.topic_id?button('Ask across project','data-broaden'):''}<div class="chat-messages">${thread.has_older?button('Earlier messages','data-older'):''}${thread.turns.length?thread.turns.map(turnHTML).join(''):'<p class="empty">Start a focused discussion. Other chat threads are not included.</p>'}</div>${pending.has(thread.id)?'<p class="notice">Checking whether your message was saved. Reconnect before retrying.</p>'+button('Check saved chat','data-check')+button('Retry same submission','data-resend'):''}<form class="chat-composer"><label class="sr-only" for="chat-message">Message</label><textarea id="chat-message" data-composer maxlength="1000" required placeholder="Ask a question or follow-up…" ${blocked?'disabled':''}>${esc(draft)}</textarea><div class="row spread"><label><input type="checkbox" data-history-context> Include memory history</label><button class="primary" ${blocked?'disabled':''}>Send</button></div><p class="helper" data-chat-status role="status">${blocked?'Response pending or needs retry.': 'Answers cite accepted memories in this scope.'}</p></form>`;
    q('[data-composer]').oninput=e=>drafts.set(thread.id,e.target.value);if(focus&&!blocked){q('[data-composer]').focus();q('[data-composer]').setSelectionRange(start,start);}
    q('[data-history]').onclick=history;q('[data-new]').onclick=()=>create(thread);q('[data-broaden]')?.addEventListener('click',()=>create({project_id:thread.project_id}));q('[data-expand]')?.addEventListener('click',()=>{expanded=onExpand(thread.id);q('[data-expand]').textContent=expanded?'Return to pane':'Expand chat';});q('[data-check]')?.addEventListener('click',()=>load(thread.id));q('[data-resend]')?.addEventListener('click',()=>submit(pending.get(thread.id)));
    q('[data-rename]').onclick=()=>{const title=prompt('Chat title',thread.title);if(title?.trim())work(async()=>{await api('/memories/chats/'+thread.id,{method:'PATCH',body:JSON.stringify({title:title.trim(),expected_version:thread.version})});onChange();await load(thread.id);});};
    q('[data-older]')?.addEventListener('click',()=>work(async()=>{const id=thread.id,d=await api(`/memories/chats/${id}?before=${thread.turns[0].sequence}`);if(valid()&&thread?.id===id){thread.turns=[...d.turns,...thread.turns];thread.has_older=d.has_older;draw();}}));
    host.querySelectorAll('[data-citation]').forEach(b=>b.onclick=()=>source(thread.turns.find(t=>t.id===b.dataset.citationTurn),b.dataset.citation));host.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>work(async()=>{const id=thread.id;await api(`/memories/chats/${id}/turns/${b.dataset.retry}/retry`,{method:'POST'});onChange();if(valid()&&thread?.id===id)await load(id);}));
    q('.chat-composer').onsubmit=e=>{e.preventDefault();const question=q('[data-composer]').value.trim();if(!question||blocked)return;submit({question,request_id:crypto.randomUUID(),expected_version:thread.version,include_history:q('[data-history-context]').checked});};
  }
  async function submit(payload){if(!payload)return;const id=thread.id;await work(async()=>{pending.set(id,payload);draw();try{const response=await api(`/memories/chats/${id}/turns/stream`,{method:'POST',body:JSON.stringify(payload),raw:true});await readChatEvents(response,message=>{if(valid()&&thread?.id===id)q('[data-chat-status]').textContent=message;});pending.delete(id);if(drafts.get(id)===payload.question)drafts.delete(id);onChange();if(valid()&&thread?.id===id)await load(id);}catch(e){if([400,409,422].includes(e.status))pending.delete(id);if(valid()&&thread?.id===id){await load(id);fail(e);}throw e;}});}
  if(threadId)load(threadId);else history();
  return ()=>{alive=false;generation++;stopPoll();sourceDialog?.close();};
}
